// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type CasestudyDocumentDataSlicesSlice =
  | CaseStudyTitleSectionSlice
  | TextBlockSlice
  | StepperSlice
  | SectionBreakSlice
  | TextBlockWithImageSlice
  | AboutMeSectionTitleSlice
  | TextBlockWithCodeSlice
  | StyledLinkSlice;

/**
 * Content for Case Study documents
 */
interface CasestudyDocumentData {
  /**
   * Slice Zone field in *Case Study*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CasestudyDocumentDataSlicesSlice> /**
   * Meta Description field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: casestudy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Case Study*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: casestudy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Case Study*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: casestudy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `casestudy`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CasestudyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CasestudyDocumentData>,
    "casestudy",
    Lang
  >;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;

  /**
   * Top Link Name field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.top_link_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  top_link_name: prismic.KeyTextField;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | ImageAndDescriptionCardSlice
  | InformationAreaSlice
  | AboutMeSectionTitleSlice
  | SectionBreakSlice
  | ImageGridSlice
  | TextBlockSlice
  | CaseStudyCardSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | CasestudyDocument
  | NavigationDocument
  | PageDocument;

/**
 * Primary content in *Header → Primary*
 */
export interface AboutMeSectionTitleSliceDefaultPrimary {
  /**
   * Title field in *Header → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_section_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Header → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_section_title.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Title Display Size field in *Header → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h2(4xl)
   * - **API ID Path**: about_me_section_title.primary.title_display_size
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  title_display_size: prismic.SelectField<"h2(4xl)" | "h3(3xl)", "filled">;

  /**
   * Title HTML Tag field in *Header → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: h2
   * - **API ID Path**: about_me_section_title.primary.title_html_tag
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  title_html_tag: prismic.SelectField<"h2" | "h3", "filled">;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeSectionTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutMeSectionTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type AboutMeSectionTitleSliceVariation = AboutMeSectionTitleSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `about_me_section_title`
 * - **Description**: AboutMeSectionTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeSectionTitleSlice = prismic.SharedSlice<
  "about_me_section_title",
  AboutMeSectionTitleSliceVariation
>;

/**
 * Primary content in *CaseStudyCards → Primary*
 */
export interface CaseStudyCardSliceDefaultPrimary {
  /**
   * Title field in *CaseStudyCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_card.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *CaseStudyCards → Items*
 */
export interface CaseStudyCardSliceDefaultItem {
  /**
   * title field in *CaseStudyCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_card.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *CaseStudyCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_card.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * type field in *CaseStudyCards → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_card.items[].type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Professional" | "Personal" | "Educational">;

  /**
   * cover image field in *CaseStudyCards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_card.items[].cover_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * page link field in *CaseStudyCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_card.items[].page_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  page_link: prismic.LinkField;
}

/**
 * Default variation for CaseStudyCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudyCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudyCardSliceDefaultPrimary>,
  Simplify<CaseStudyCardSliceDefaultItem>
>;

/**
 * Slice variation for *CaseStudyCards*
 */
type CaseStudyCardSliceVariation = CaseStudyCardSliceDefault;

/**
 * CaseStudyCards Shared Slice
 *
 * - **API ID**: `case_study_card`
 * - **Description**: CaseStudyCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudyCardSlice = prismic.SharedSlice<
  "case_study_card",
  CaseStudyCardSliceVariation
>;

/**
 * Primary content in *CaseStudyTitleSection → Primary*
 */
export interface CaseStudyTitleSectionSliceDefaultPrimary {
  /**
   * Background Image field in *CaseStudyTitleSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_title_section.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Main Title field in *CaseStudyTitleSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_title_section.primary.main_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_title: prismic.KeyTextField;

  /**
   * Sub Title field in *CaseStudyTitleSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_title_section.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Description field in *CaseStudyTitleSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_title_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *CaseStudyTitleSection → Items*
 */
export interface CaseStudyTitleSectionSliceDefaultItem {
  /**
   * Tag field in *CaseStudyTitleSection → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study_title_section.items[].tag
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tag: prismic.SelectField<
    | "Product Design"
    | "UI Design"
    | "Mockup Creation"
    | "Figma"
    | "Advisor/Review"
    | "User Tests"
    | "User Interviews"
    | "User Research"
    | "Logo Creation"
    | "Rapid Prototyping"
    | "Tangible Product"
  >;
}

/**
 * Default variation for CaseStudyTitleSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudyTitleSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudyTitleSectionSliceDefaultPrimary>,
  Simplify<CaseStudyTitleSectionSliceDefaultItem>
>;

/**
 * Slice variation for *CaseStudyTitleSection*
 */
type CaseStudyTitleSectionSliceVariation = CaseStudyTitleSectionSliceDefault;

/**
 * CaseStudyTitleSection Shared Slice
 *
 * - **API ID**: `case_study_title_section`
 * - **Description**: CaseStudyTitleSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CaseStudyTitleSectionSlice = prismic.SharedSlice<
  "case_study_title_section",
  CaseStudyTitleSectionSliceVariation
>;

/**
 * Primary content in *ImageAndTextCard → Primary*
 */
export interface ImageAndDescriptionCardSliceDefaultPrimary {
  /**
   * image field in *ImageAndTextCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_description_card.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * text field in *ImageAndTextCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_description_card.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Title field in *ImageAndTextCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_description_card.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ImageAndTextCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndDescriptionCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndDescriptionCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageAndTextCard*
 */
type ImageAndDescriptionCardSliceVariation =
  ImageAndDescriptionCardSliceDefault;

/**
 * ImageAndTextCard Shared Slice
 *
 * - **API ID**: `image_and_description_card`
 * - **Description**: ImageAndDescriptionCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndDescriptionCardSlice = prismic.SharedSlice<
  "image_and_description_card",
  ImageAndDescriptionCardSliceVariation
>;

/**
 * Primary content in *ImageGrid → Items*
 */
export interface ImageGridSliceDefaultItem {
  /**
   * Image field in *ImageGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_grid.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageGridSliceDefaultItem>
>;

/**
 * Slice variation for *ImageGrid*
 */
type ImageGridSliceVariation = ImageGridSliceDefault;

/**
 * ImageGrid Shared Slice
 *
 * - **API ID**: `image_grid`
 * - **Description**: ImageGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGridSlice = prismic.SharedSlice<
  "image_grid",
  ImageGridSliceVariation
>;

/**
 * Primary content in *AboutMeInfoArea → Primary*
 */
export interface InformationAreaSliceDefaultPrimary {
  /**
   * Title Image field in *AboutMeInfoArea → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.primary.title_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  title_image: prismic.ImageField<never>;

  /**
   * Title field in *AboutMeInfoArea → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Title field in *AboutMeInfoArea → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Description field in *AboutMeInfoArea → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AboutMeInfoArea → Items*
 */
export interface InformationAreaSliceDefaultItem {
  /**
   * Text Area field in *AboutMeInfoArea → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.items[].text_area
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_area: prismic.RichTextField;
}

/**
 * Default variation for AboutMeInfoArea Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationAreaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InformationAreaSliceDefaultPrimary>,
  Simplify<InformationAreaSliceDefaultItem>
>;

/**
 * Primary content in *AboutMeInfoArea → Primary*
 */
export interface InformationAreaSliceSimplePrimary {
  /**
   * Title field in *AboutMeInfoArea → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Title field in *AboutMeInfoArea → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;

  /**
   * Description field in *AboutMeInfoArea → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Simple variation for AboutMeInfoArea Slice
 *
 * - **API ID**: `simple`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationAreaSliceSimple = prismic.SharedSliceVariation<
  "simple",
  Simplify<InformationAreaSliceSimplePrimary>,
  never
>;

/**
 * Primary content in *AboutMeInfoArea → Items*
 */
export interface InformationAreaSliceRepeatableListOnlyItem {
  /**
   * Text Area field in *AboutMeInfoArea → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_area.items[].text_area
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_area: prismic.RichTextField;
}

/**
 * Repeatable List Only variation for AboutMeInfoArea Slice
 *
 * - **API ID**: `repeatableListOnly`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationAreaSliceRepeatableListOnly =
  prismic.SharedSliceVariation<
    "repeatableListOnly",
    Record<string, never>,
    Simplify<InformationAreaSliceRepeatableListOnlyItem>
  >;

/**
 * Slice variation for *AboutMeInfoArea*
 */
type InformationAreaSliceVariation =
  | InformationAreaSliceDefault
  | InformationAreaSliceSimple
  | InformationAreaSliceRepeatableListOnly;

/**
 * AboutMeInfoArea Shared Slice
 *
 * - **API ID**: `information_area`
 * - **Description**: InformationArea
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationAreaSlice = prismic.SharedSlice<
  "information_area",
  InformationAreaSliceVariation
>;

/**
 * Default variation for SectionBreak Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionBreakSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *SectionBreak*
 */
type SectionBreakSliceVariation = SectionBreakSliceDefault;

/**
 * SectionBreak Shared Slice
 *
 * - **API ID**: `section_break`
 * - **Description**: SectionBreak
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SectionBreakSlice = prismic.SharedSlice<
  "section_break",
  SectionBreakSliceVariation
>;

/**
 * Primary content in *Stepper → Items*
 */
export interface StepperSliceDefaultItem {
  /**
   * Title field in *Stepper → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stepper.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Stepper → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stepper.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Stepper Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepperSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StepperSliceDefaultItem>
>;

/**
 * Slice variation for *Stepper*
 */
type StepperSliceVariation = StepperSliceDefault;

/**
 * Stepper Shared Slice
 *
 * - **API ID**: `stepper`
 * - **Description**: Stepper
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StepperSlice = prismic.SharedSlice<
  "stepper",
  StepperSliceVariation
>;

/**
 * Primary content in *CardLinks → Items*
 */
export interface StyledLinkSliceDefaultItem {
  /**
   * Title field in *CardLinks → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: styled_link.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *CardLinks → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: styled_link.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * hasQR field in *CardLinks → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: styled_link.items[].hasqr
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  hasqr: prismic.BooleanField;

  /**
   * cover Image field in *CardLinks → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: styled_link.items[].cover_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * URL field in *CardLinks → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: styled_link.items[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;
}

/**
 * Default variation for CardLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StyledLinkSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StyledLinkSliceDefaultItem>
>;

/**
 * Slice variation for *CardLinks*
 */
type StyledLinkSliceVariation = StyledLinkSliceDefault;

/**
 * CardLinks Shared Slice
 *
 * - **API ID**: `styled_link`
 * - **Description**: StyledLink
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StyledLinkSlice = prismic.SharedSlice<
  "styled_link",
  StyledLinkSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Text field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

/**
 * Primary content in *TextBlockWithCode → Primary*
 */
export interface TextBlockWithCodeSliceDefaultPrimary {
  /**
   * Text field in *TextBlockWithCode → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_with_code.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Code field in *TextBlockWithCode → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_with_code.primary.code
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  code: prismic.KeyTextField;
}

/**
 * Default variation for TextBlockWithCode Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockWithCodeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockWithCodeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlockWithCode*
 */
type TextBlockWithCodeSliceVariation = TextBlockWithCodeSliceDefault;

/**
 * TextBlockWithCode Shared Slice
 *
 * - **API ID**: `text_block_with_code`
 * - **Description**: TextBlockWithCode
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockWithCodeSlice = prismic.SharedSlice<
  "text_block_with_code",
  TextBlockWithCodeSliceVariation
>;

/**
 * Primary content in *TextBlockWithImage → Items*
 */
export interface TextBlockWithImageSliceDefaultItem {
  /**
   * Text field in *TextBlockWithImage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_with_image.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextBlockWithImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_with_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TextBlockWithImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockWithImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<TextBlockWithImageSliceDefaultItem>
>;

/**
 * Primary content in *TextBlockWithImage → Items*
 */
export interface TextBlockWithImageSliceImageOnRightItem {
  /**
   * Text field in *TextBlockWithImage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_with_image.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextBlockWithImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_with_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Image On Right variation for TextBlockWithImage Slice
 *
 * - **API ID**: `imageOnRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockWithImageSliceImageOnRight = prismic.SharedSliceVariation<
  "imageOnRight",
  Record<string, never>,
  Simplify<TextBlockWithImageSliceImageOnRightItem>
>;

/**
 * Primary content in *TextBlockWithImage → Items*
 */
export interface TextBlockWithImageSliceTwoColumnItem {
  /**
   * Text field in *TextBlockWithImage → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_with_image.items[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Image field in *TextBlockWithImage → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block_with_image.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * TwoColumn variation for TextBlockWithImage Slice
 *
 * - **API ID**: `twoColumn`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockWithImageSliceTwoColumn = prismic.SharedSliceVariation<
  "twoColumn",
  Record<string, never>,
  Simplify<TextBlockWithImageSliceTwoColumnItem>
>;

/**
 * Slice variation for *TextBlockWithImage*
 */
type TextBlockWithImageSliceVariation =
  | TextBlockWithImageSliceDefault
  | TextBlockWithImageSliceImageOnRight
  | TextBlockWithImageSliceTwoColumn;

/**
 * TextBlockWithImage Shared Slice
 *
 * - **API ID**: `text_block_with_image`
 * - **Description**: TextBlockWithImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockWithImageSlice = prismic.SharedSlice<
  "text_block_with_image",
  TextBlockWithImageSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CasestudyDocument,
      CasestudyDocumentData,
      CasestudyDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutMeSectionTitleSlice,
      AboutMeSectionTitleSliceDefaultPrimary,
      AboutMeSectionTitleSliceVariation,
      AboutMeSectionTitleSliceDefault,
      CaseStudyCardSlice,
      CaseStudyCardSliceDefaultPrimary,
      CaseStudyCardSliceDefaultItem,
      CaseStudyCardSliceVariation,
      CaseStudyCardSliceDefault,
      CaseStudyTitleSectionSlice,
      CaseStudyTitleSectionSliceDefaultPrimary,
      CaseStudyTitleSectionSliceDefaultItem,
      CaseStudyTitleSectionSliceVariation,
      CaseStudyTitleSectionSliceDefault,
      ImageAndDescriptionCardSlice,
      ImageAndDescriptionCardSliceDefaultPrimary,
      ImageAndDescriptionCardSliceVariation,
      ImageAndDescriptionCardSliceDefault,
      ImageGridSlice,
      ImageGridSliceDefaultItem,
      ImageGridSliceVariation,
      ImageGridSliceDefault,
      InformationAreaSlice,
      InformationAreaSliceDefaultPrimary,
      InformationAreaSliceDefaultItem,
      InformationAreaSliceSimplePrimary,
      InformationAreaSliceRepeatableListOnlyItem,
      InformationAreaSliceVariation,
      InformationAreaSliceDefault,
      InformationAreaSliceSimple,
      InformationAreaSliceRepeatableListOnly,
      SectionBreakSlice,
      SectionBreakSliceVariation,
      SectionBreakSliceDefault,
      StepperSlice,
      StepperSliceDefaultItem,
      StepperSliceVariation,
      StepperSliceDefault,
      StyledLinkSlice,
      StyledLinkSliceDefaultItem,
      StyledLinkSliceVariation,
      StyledLinkSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
      TextBlockWithCodeSlice,
      TextBlockWithCodeSliceDefaultPrimary,
      TextBlockWithCodeSliceVariation,
      TextBlockWithCodeSliceDefault,
      TextBlockWithImageSlice,
      TextBlockWithImageSliceDefaultItem,
      TextBlockWithImageSliceImageOnRightItem,
      TextBlockWithImageSliceTwoColumnItem,
      TextBlockWithImageSliceVariation,
      TextBlockWithImageSliceDefault,
      TextBlockWithImageSliceImageOnRight,
      TextBlockWithImageSliceTwoColumn,
    };
  }
}
