// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_me_section_title: dynamic(() => import("./Header")),
  case_study_card: dynamic(() => import("./CaseStudyCards")),
  case_study_title_section: dynamic(() => import("./CaseStudyTitleSection")),
  image_and_description_card: dynamic(() => import("./ImageAndTextCard")),
  image_grid: dynamic(() => import("./ImageGrid")),
  information_area: dynamic(() => import("./AboutMeInfoArea")),
  section_break: dynamic(() => import("./SectionBreak")),
  stepper: dynamic(() => import("./Stepper")),
  styled_link: dynamic(() => import("./CardLinks")),
  text_block: dynamic(() => import("./TextBlock")),
  text_block_with_code: dynamic(() => import("./TextBlockWithCode")),
  text_block_with_image: dynamic(() => import("./TextBlockWithImage")),
};
